definitions:
  StockResponceDto:
    properties:
      avarage_3_month_volume:
        type: string
      change:
        type: number
      created_at_unix:
        description: CreatedAt          string  `json:"created_at_date_utc"`
        type: integer
      market_cap:
        type: string
      name:
        type: string
      pe_ratio:
        type: string
      percent_change:
        type: number
      price:
        type: number
      symbol:
        type: string
      volume:
        type: string
    type: object
  utils.Error:
    properties:
      errors:
        additionalProperties: true
        type: object
    type: object
info:
  contact: {}
paths:
  /stocks/:
    get:
      consumes:
      - application/json
      description: Get an actually stocks. Auth not required
      operationId: get
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/StockResponceDto'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/utils.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/utils.Error'
      summary: Get actually stocks
      tags:
      - stocks
swagger: "2.0"
